### ISSUE TITLE
Release a single jar containing all dependencies.

### ISSUE THREAD

**Issue by croesch** [joel-costigliola/assertj-swing#110]
_Issue by **[Alex Ruiz](http://jira.codehaus.org/secure/ViewProfile.jspa?name=alexruiz)** from Mon, 27 Apr 2009 17:51:20 -0500_
_Originally opened as http://jira.codehaus.org/browse/FEST-116_

---

<p>From Eric Kolotyluk:</p>

<p>Is there some reason you don't have something like fest-all.jar somewhere to make life easier? Having to include 4 or 5 libraries just to get started seems a little excessive and overly complicated to me.</p>

---

votes (original issue): 1
watches (original issue): 0

**Comment by Neitsch** [comment]
You should be able to achieve this with this plugin
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.4.1</version>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
				  <execution>
					<id>make-assembly</id>
					<phase>package</phase> 
					<goals>
						<goal>single</goal>
					</goals>
				  </execution>
				</executions>
			</plugin>
