### ISSUE TITLE
Race condition in BasicRobot.focus(Component target, boolean wait) - results in ActionFailedException

### ISSUE THREAD

**Issue by croesch** [joel-costigliola/assertj-swing#12]
_Issue by **[brettvascon](https://github.com/brettvascon)** from Tuesday Aug 28, 2012 at 20:44 GMT_
_Originally opened as https://github.com/alexruiz/fest-swing-1.x/issues/3_

----

We are hitting this quite frequently, since focus runs on the main thread, it is possible for the focus change to occur between the call to inEdtFocusOwner and the call to FocusMonitor.attachTo(target) in the code below:

```java
  private void focus(Component target, boolean wait) {
    Component currentOwner = inEdtFocusOwner();
    if (currentOwner == target) return;
    FocusMonitor focusMonitor = FocusMonitor.attachTo(target);
```

The result is that focusMonitor never gets a focusGained event since the focus transition has already occurred, and therefore hasFocus returns false even though focus has indeed changed to the target. The timeout loop further down ends up throwing an  ActionFailedException "Focus change to X failed"

The fix would be to call inEdtFocusOwner() again after the attachTo call, and if it returns the target, remove the focus listener and return.

**Comment by baudren** [comment]
Hi @croesch, I am experiencing problems with what I think is this issue, right now.

While testing a ComboBox with autocomplete, sometimes, the test hangs unexpectedly, and results in this stack trace:

~~~ java
ActionFailedException: Focus change to org.yccheok.jstock.gui.AutoCompleteJComboBox[name=null, selectedItem=AAPL, contents=[AAPL, AAPL34.SA, AAPL.MX, AAPL.BA, AAPL.SW, AAPL34F.SA, ^AIX, ^AVSPY, DE3WB5.TI], editable=true, enabled=true, visible=true, showing=false] failed focus owner: Null Component
~~~

Any estimate as to when this problem would be tackled, or a workaround in the meantime?

Thanks in advance,

**Comment by baudren** [comment]
@croesh,

I implemented a fix, as described in the original method. It now reads

~~~ java
  private void focus(Component target, boolean wait) {
    Component currentOwner = inEdtFocusOwner();
    if (currentOwner == target) return;
    FocusMonitor focusMonitor = FocusMonitor.attachTo(target);
    Component newOwner = inEdtFocusOwner();
    if (newOwner == target) {
      target.removeFocusListener(focusMonitor);
      return;
    }
    // for pointer focus
    moveMouse(target);
    ...
~~~

The problem seems to be mitigated, but leads to `NullPointerException` along the way:

~~~
Exception in thread "pool-4-thread-1" java.lang.NullPointerException
        at org.yccheok.jstock.engine.Utils.getStocksCSVZipFileLocation(Utils.java:343)
        at org.yccheok.jstock.gui.JStock$74.run(JStock.java:3945)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
~~~

Is my implementation to straightforward, did I miss something? Since I am not at all familiar with the source code, it probably is the case. Should the `removeListener` be on `target`?

**Comment by croesch** [comment]
Hi @baudren 

thanks for your fix. I'm not sure what's the problem with the `NullPointerException`. I would guess it's not part of AssertJ-Swing - could you paste the code at

```
        at org.yccheok.jstock.engine.Utils.getStocksCSVZipFileLocation(Utils.java:343)
```

**Comment by baudren** [comment]
Thanks for the feedback, @croesch 
Unfortunately, while I still have access to the code from an old version, this part of the code [is now considered closed-source](https://github.com/yccheok/jstock/tree/master/src/org/yccheok/jstock/engine). I would therefore not push the inquiry, and it indeed seems to be a problem on their side.

Do you intend to merge the fix in a future release? I did not run the tests - they take a really long time to go through on my machine. Without testing, I did not want to open a PR (and I did not see a CI environment on Github, though there might be one?).

**Comment by croesch** [comment]
I will merge the fix in a future release. CI is not set up. As I'm still working on getting all tests green - *shame on me*.

But don't hesitate to file PRs in future!

**Comment by croesch** [comment]
Merged. Hopefully fixed ;-)

**Comment by baudren** [comment]
Great, thank you!
