### ISSUE TITLE
Regression in requireVisible

### ISSUE THREAD

**Issue by sebastian-koster** [joel-costigliola/assertj-swing#148]
This looks like an [old issue](http://jira.codehaus.org/browse/FEST-429) from fest-assert 1.4 and fest-swing 1.2 that I was trying to avoid by using AssertJ. I got the below exception using assert-core 1.7.0 and assertj-swing-junit-4.5 1.0.0.

`java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Z)Lorg/assertj/core/api/BooleanAssert;
	at org.assertj.swing.driver.ComponentDriver.requireVisible(ComponentDriver.java:219)
	at org.assertj.swing.fixture.AbstractComponentFixture.requireVisible(AbstractComponentFixture.java:357)`

**Comment by stefanovaleri** [comment]
I got same exception using 
 - assert-core 1.7.1
 - assertj-swing-1.1.0
 - assertj-swing-junit-1.1.0
 - assertj-swing-junit-4.5-1.1.0

**Comment by bbobcik** [comment]
I wonder if there is some problem with JAR assembly of Maven artifacts, because putting an equivalent of requireVisible() directly to the test code, e.g.
````java
import static org.assertj.core.api.Assertions.assertThat;

final JTableFixture table = window.table("testTable");
final JTable jtable = table.target();
final boolean visible = ComponentVisibleQuery.isVisible(jtable);
assertThat(visible).as(ComponentDriver.propertyName(jtable, "visible")).isTrue();
````
works normally, whereas code
````java
final JTableFixture table = window.table("testTable");
table.requireVisible();
````
fails with the NoSuchMethodError. I was not able to notice any problems with classloading.

**Comment by croesch** [comment]
Thanks for the analysis! Moving from FEST to AssertJ I did some maven dependency juggling. So that might have caused the reason, I'm going to have a look at it.

**Comment by croesch** [comment]
It seems that there is an incompatibility between `assertj-core:1.6.0` and `assertj-core:1.7.0`. I got the same error in the `assertj-swing-junit-examples` when I added `assertj-core` as additional dependency.

Can you verify that the error disappears when you're using the `assertj-core` version referenced by `assertj-swing`?

If so, I would suggest just adding
```
<dependency>
  <groupId>org.assertj</groupId>
  <artifactId>assertj-swing-junit-4.5</artifactId>
  <version>1.1.0</version>
  <scope>test</scope>
</dependency>
```

As dependency. For `assertj-swing` this should definitely be the only dependency you reference in your pom. For `assertj-core` I understand it's a problem that you don't have the newest version of `assertj-core` when using `assertj-swing`.

Therefore I would suggest releasing an `assertj-swing` version compatible with the latest `1.7.x` release of the core and one being compatible with the latest `2.0.x` version of `assertj-core`.

**Comment by croesch** [comment]
Released `assertj-swing:1.2.0` with `assertj-core:1.7.1` this should fix this issue. Please reopen if not :-)

**Comment by sebastian-koster** [comment]
Sorry for the delay, finally got around to testing this again, and it works! Thanks croesch!

**Comment by croesch** [comment]
Don't worry, since the real delay is always on my side I'm the one who needs to apologise ;-)

Glad it helps!
