### ISSUE TITLE
JIDE support

### ISSUE THREAD

**Issue by gschrader** [joel-costigliola/assertj-swing#149]
I found the old jide fest source code [here](https://github.com/codehaus/fest-git/tree/master/fest-swing-jide) (I'm not sure if that's the original or not) that I was able to convert to assertj-swing.  I'm just wondering if you would like to have it as part of this repository (I would do a pull request).  There maybe isn't that many people that even require it any more so maybe it's not worth it for you.  If not, I'll push it somewhere else in case anyone else needs it.

**Comment by croesch** [comment]
Okay, I didn't hear from them since then..

I wrote a mail today, got a quick reply, got the code compiling locally. I'm going to get the licence requirements satisfied now, which might just be a link to their website. But I'm mailing with them to be sure..

**Comment by croesch** [comment]
support@jidesoft:
> If you just compile against it, no need to acknowledge using JIDE.

-> PR merged.

**Comment by croesch** [comment]
Relesead 1.1.0 of assertj-swing containing jide support.
