### ISSUE TITLE
Pause Keeps Checking Condition after Timeout

### ISSUE THREAD

**Issue by michaelfletcheratwork** [joel-costigliola/assertj-swing#152]
When a pause on a condition times out the condition will still be checked after the timeout.

Unfortunately we have some long running tests jobs that have a few tests timing out.  We are finding that after a period of time (3 hours) we have dozens of threads in the Pause.EXECUTOR_SERVICE threadpools has 30 threads checking conditions which then is burning the entire Event Dispatch Thread which I assume is then causing more timeouts.

When the change was made to use the threadpool it no longer attempts to stop checking the condition if the condition times out.

**Comment by croesch** [comment]
Thanks for your investigations and for the patch. I'm not really on these days, but I'll have a deeper look at the patch and the problem this or next week.

But my current assumption is, that it could be enough checking for the timeout in the while-loop as the executor should already have thrown an exception. To be sure, I'll doublecheck that and contact you again!

**Comment by croesch** [comment]
>  but I'll have a deeper look at the patch and the problem this or next week.

m( sorry!

Thanks for your help and PR. I merged the code, it will be part of the 2.0.0 release which is not yet released. I slightly (IMO) improved the implementation by using the cancel-mechanism provided by the Callable interface. Works quite well.

HTH :)
