### ISSUE TITLE
java.lang.NoClassDefFoundError: org/assertj/core/util/SystemProperties

### ISSUE THREAD

**Issue by javier-jimenez** [joel-costigliola/assertj-swing#161]
BasicComponentFinder.java contains static includes and usages of org.assertj.core.util.SystemProperties.LINE_SEPARATOR which is no longer in the assertj-core

This causes java.lang.NoClassDefFoundError exceptions when the includeHierarchyIfComponentNotFound is enabled.

Using versions:
assertj-swing-testng 2.1.0
assertj-core 3.1.0

**Comment by croesch** [comment]
Hi @javier-jimenez 

assertj-swing is compatible with assertj-core 2.0.0. So to avoid that kind of errors please don't include assertj-core 3.x with assertj-swing 2.x.

I'll provide a compatible version soon. So that you can use assertj-swing with assertj-core 3.x.

**Comment by javier-jimenez** [comment]
Thank you @croesch ! As a temporary workaround I simply copied the SystemProperties.java class in my workspace.. but definitely your changes are the way to go!

**Comment by croesch** [comment]
You're welcome :) There are a couple of other problems, please see the commit above for the full list of incompatibilities between `assertj-core` 2.0.0 and 3.1.0 that effect `assertj-swing` directly.

So at least there might be a couple of other class files you should add. But be aware :) Preferred solution: check out commit above; do `$ mvn clean install` use the local SNAPSHOT release. If problems occur let me know!

As soon as the new parent pom is available, I'll go for merging the changes to release AssertJ Swing 3.0.0.
