### ISSUE TITLE
Assertj-swing 2.1.0 and 2.1.1 is incompatible with assertj-core 2.1.0

### ISSUE THREAD

**Issue by wjbakker** [joel-costigliola/assertj-swing#162]
In the latest assertj-swing-junit 2.1.0 and 2.1.1 releases, the FolderCreator class imports FilesException from:

```java
import org.assertj.core.util.FilesException
```

The FilesException class no longer exists in this package in assertj-core 2.1.0

**Comment by croesch** [comment]
Thanks for your help - I'll release a 2.x.x compatible release today. In the meantime, 2.0.0 of assertj-core should be compatible with assertj-swing 2.1.1.

**Comment by croesch** [comment]
2.2.0 of assertj-swing is compatible with 2.2.0 of assertj-core. Released. Closing :)
