### ISSUE TITLE
assertj-swing-junit-4.5: last Maven version 

### ISSUE THREAD

**Issue by lbalazscs** [joel-costigliola/assertj-swing#163]
I use JUnit 4.12, so if I understand correctly, I should use the package with the artifact id assertj-swing-junit-4.5 instead of assertj-swing-junit. However, the last version of assertj-swing-junit-4.5 (1.2.0) pulls some old versions as Maven dependencies: 1.2.0 for assertj-swing-junit and assertj-swing (newest version: 2.1.1), and these depend on the seemingly really old 1.7.1 version of assertj-core (newest version: 3.1.0)

![screen](https://cloud.githubusercontent.com/assets/9939454/9283642/9f9d3548-42d5-11e5-934b-b56a79f9bd93.png)

As far as I understand, assertj-swing-junit-4.5 should have a newer version that depends on the newest version of the other packages.

**Comment by croesch** [comment]
With assertj-swing 2.0.0 I removed support for JUnit 4.3.x. So now JUnit users just need assertj-swing-junit.

So if you're using maven you should just have one dependency:
```
<dependency>
  <groupId>org.assertj</groupId>
  <artifactId>assertj-swing-junit</artifactId>
  <version>2.1.1</version>
  <scope>test</scope>
</dependency>
```

If this helps - fine. If not please reopen the issue and give further details.
