### ISSUE TITLE
NoClassDefFoundError: org/fest/reflect/exception/ReflectionError without fest-reflect

### ISSUE THREAD

**Issue by hbruch** [joel-costigliola/assertj-swing#167]
When creating a new FrameFixture(frame), I get a 
java.lang.NoClassDefFoundError: org/fest/reflect/exception/ReflectionError
	at org.assertj.swing.input.InputState.<init>(InputState.java:56)
	at org.assertj.swing.core.BasicRobot.<clinit>(BasicRobot.java:119)
	at org.assertj.swing.fixture.AbstractWindowFixture.<init>(AbstractWindowFixture.java:116)
	at org.assertj.swing.fixture.FrameFixture.<init>(FrameFixture.java:43)
...

After adding fest-reflect to the pom, it worked. The assertj-swing pom.xml states fest-reflect as optional, but it seems to be needed, at least when running with junit 4.11?

**Comment by croesch** [comment]
Indeed `fest-reflect` and `fest-util` is missing. It should be included in the assertj-swing jar. It is marked as optional yes, but at least until 2.1.0 that worked well :)

I'm trying to find out how to include it again. Thanks for reporting!

**Comment by croesch** [comment]
It turned out that jarjar-maven-plugin was not working well. I updated it to 1.9 and the jar seems to be good now. Running the AssertJ Swing examples worked well, too - so I think this is fixed.

Can you verify that?
