### ISSUE TITLE
FrameFixture should expose `requireTitle`

### ISSUE THREAD

**Issue by Vogel612** [joel-costigliola/assertj-swing#181]
Sometimes I have a frame where I'd change the title, depending on the current state of the program.

To allow unit-testing this, a way to verify the title in a test is needed.

Judging by the other methods exposed, `requireTitle(String)` should be acceptable

**Comment by croesch** [comment]
Thanks for the request. Done and will be part of the next release :)

**Comment by croesch** [comment]
Part of 3.5.0
