### ISSUE TITLE
Ability to unselect rows on a JTableFixture

### ISSUE THREAD

**Issue by fedelopez** [joel-costigliola/assertj-swing#182]
Currently the `JTableFixture` allows selecting one or more rows via the method `selectRows(int... rows)`. It would be very useful to have a method which allows unselecting rows too.

My current workaround is the following: 

    tableFixture.selectRows(row);
    ...
    tableFixture.pressKey(KeyEvent.VK_CONTROL);
    TableCellInSelectedRow column = new TableCellInSelectedRow.TableCellBuilder().column(0);
    tableFixture.cell(column).click();
    tableFixture.releaseKey(KeyEvent.VK_CONTROL);

Is there a better way to unselect a row?

**Comment by croesch** [comment]
Currently there is no good way. You can use `Platform.controlOrCommandKey()` instead of the control key .. but there's no support for deselecting rows. Not yet :)

**Comment by croesch** [comment]
Contained in 3.3.0
