### ISSUE TITLE
Drop a List or Tree item item above or below a specified item

### ISSUE THREAD

**Issue by LindsayPeters** [joel-costigliola/assertj-swing#183]
Currently the <code>JTreeFixture</code> and <code>JListFixture</code> allow dropping an item onto a specified JTree or JList row or item. Is there any way to drop an item just above or below a specified item, i.e. as you would when using DnD to reorder a list?

**Comment by croesch** [comment]
Currently there is no support for this. Obviously you could call `drop(int)` with de/incrementing the index. Would it help to add methods like `dropAbove(int/String)` and `dropBelow(int/String)` which would do this internally?

**Comment by LindsayPeters** [comment]
Hi Christian,

Thanks for the response. However, drop(n) drops onto the item at index n. What we need is the ability to drop an item just before the item at n, i.e. between the items at n-1 and n.

Lindsay

**Comment by croesch** [comment]
Hello Lindsay,

that's what I meant. Calling `drop(n-1)` or `drop(n+1)`. I guess adding the methods above wouldn't cost that much. And might appear in the next release :)

**Comment by croesch** [comment]
Let me know if more methods are needed / helpful :)
