### ISSUE TITLE
GUI-Tests on a headless CI-server (Windows)

### ISSUE THREAD

**Issue by ThiAmm** [joel-costigliola/assertj-swing#188]
Hello,

i wrote some GUI-Tests using Assertj-Swing and now want to execute the GUI-Tests on a headless Jenkins-server. The GUI-tests however are failing because every time a button which is linked to opening a new frame is clicked, the frame is not showing (i assume this is because assertj assumes a button on a position, where no button is visible). This results in a WaitTimedOutError. The GUI-Tests are passing, if i am linked to the headless server via RDC.

So, my question is if it is possible to execute GUI-Tests using AssertJ-Swing on a headless Windows-server?

**Comment by croesch** [comment]
This has been asked and answered on the [mailing list](https://groups.google.com/forum/#!topic/assertj/d37ln-zGgoM) these days. Please feel free to reopen if the answer is not helpful.

**Comment by ThiAmm** [comment]
Hello,
[This answer is a reference to the answer of @croesch on the [mailing list](https://groups.google.com/forum/#!topic/assertj/d37ln-zGgoM)]

unfortunately i am not able to execute a test with assertj-swing on Jenkins successfully. Here is the basic problem i have: Suppose i do have a frame with a button on it, which opens up a new frame on clicking the button.

Here is the test, which fails on Jenkins:

```
    @Test(timeout = 60000)
    public void testWinAnl(){
        Robot r = TestUtils.getStdRobot();
        JFrame fr = new JFrame();
        fr.setSize(300, 300);
        fr.setName("Frame1");
        JButton jb = new JButton("TEst");
        final JFrame jf = new JFrame();
        jb.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                jf.setSize(300, 300);
                jf.setVisible(true);
                jf.setTitle("Blabla");
                jf.setName("Frame2");
            }
        });
        fr.add(jb);
        fr.setVisible(true);
        
        FrameFixture fixFr1 = findFrame("Frame1").using(r);
        JButtonFixture jbf = fixFr1.button();
        jbf.click();
        FrameFixture fixFr2 = findFrame("Frame2").using(r);
    }
```


Here is the static method getStdRobot from Testutils:

```
public static Robot getStdRobot() {
        Robot r = BasicRobot.robotWithCurrentAwtHierarchyWithoutScreenLock();
        r.settings().delayBetweenEvents(1);
        return r;
}
```

I always get a org.assertj.swing.exception.WaitTimedOutError and this is because assertj is not able to find the frame "Frame2", which was opened by clicking on the button. The first frame was found. 

Can you specify what you mean by "Running AssertJ Swing under a vnc server"?
I don't understand the description on the page of assertj.
