### ISSUE TITLE
Robot.click at button or menuitem do not happen same times

### ISSUE THREAD

**Issue by bernardobreder** [joel-costigliola/assertj-swing#190]
Hello, I have used fest-swing in a big project and I am trying to migrate to assertj-swing framework. Since the beginning using fest-swing, sometimes the feature in the robot click does not function so well. For instance, I have 100 tests and 5 tests break due to robot do not click at the button or in a menuitem. Can you help me about this? Do you know what is happening? The assertj-swing solved some similar problem ?

**Comment by bernardobreder** [comment]
I created a simple code test to demonstrate the problem. I figure out that there are two break situations only: 
1. The robot is trying to execute a requireText before the input text to be ready. (See figure test1.jpg) 
2. The robot fills the input, click the button and gives an error in requireText method (see figure test2.jpg)

The test code file is attached. 

Did anyone have this problem or know how circumvents it.

![test1](https://cloud.githubusercontent.com/assets/767842/19388876/11fd1d70-91f8-11e6-9252-29b43d120bf7.jpg)
![test2](https://cloud.githubusercontent.com/assets/767842/19388877/11ff2534-91f8-11e6-9e45-7065df5b88fc.jpg)
[AJFrameFixtureTest.java.zip](https://github.com/joel-costigliola/assertj-swing/files/529585/AJFrameFixtureTest.java.zip)

**Comment by croesch** [comment]
Hi thanks for providing your problem and the additional information (including the test) - that helps!

What information of AssertJ Swing are you running? Indeed there are a lot of little problems like this and I'm hunting for them to remove them. With 3.4.0 I released a fix that might solve a lot of these problems. Could you check your problem with 3.4.0? I add your test to the test suite but *unfortunately* the test runs successful on my machine with the latest code.

So please let me know if the latest release works for you, too. Thanks!

**Comment by croesch** [comment]
Reopen if it still exists.
