### ISSUE TITLE
Exception within Settings

### ISSUE THREAD

**Issue by slowjack2k** [joel-costigliola/assertj-swing#194]
Hi,

`Settings.getGeneric` has an issue with `Properties`. Instead of variable `properties, variable [systemProperty](https://github.com/joel-costigliola/assertj-swing/blob/ec6cdb0340b34205bd7c686898026d2e4bea9144/assertj-swing/src/main/java/org/assertj/swing/core/Settings.java#L99) is used. When no SystemProperty is set, this leads to an exception.

regards
dieter

**Comment by croesch** [comment]
Hi Dieter,

thank you very much.

**Comment by croesch** [comment]
Part of 3.5.0
