### ISSUE TITLE
Add logging info

### ISSUE THREAD

**Issue by fmarot** [joel-costigliola/assertj-swing#198]
Hi, I've just started using AsserJ-swing and it's cool, thank you :)
But I had problems debugging wrong keys being sent on my Continuous Integration server. Also had problems understanding what happened behind the scenes regarding the KeyStrokeMapping features.

So I think it would be very helpfull to use a logging framework so that users may activate logging and figure out what really happens.
If you think this is a good idea, SLF4J may be all what you need ;)
Logging level could be set to "debug" or "trace" by default.

Regards

**Comment by croesch** [comment]
Thanks for the suggestion. It might take some time until this get's done (like this answer ;) ). But I agree, it might be helpful..

**Comment by croesch** [comment]
Similar to #123

**Comment by croesch** [comment]
Contained in 3.8.0
