### ISSUE TITLE
Add a way to force the use a pre-defined KeyStrokeMappingProvider

### ISSUE THREAD

**Issue by fmarot** [joel-costigliola/assertj-swing#199]
Hello,

I recently faced problems running GUI tests on Jenkins on a Linux slave using XVFB. The linux was configured in French, but XVFB in english, and I did not really understood what was happening and why the wrong keys were being sent (I received "&" instead of "1" for instance in textfields).

I finally understood the auto-discovery of KeyStrokeMappingProvider through Locale but it did not work correctly for me either. Finally, I hacked through your sources to add a command line property (like -DKeyStrokeMappingProvider=KeyStrokeMappingProvider_en on the command line) to be able to force the "en" Provider and bypass the auto-detection.

So my suggestion is to be able to override auto-detection. I can provide a patch if you're interested (please tell me the way you see it).

Regards

**Comment by croesch** [comment]
Hi @fmarot 

Thanks for sharing this information. Unfortunately the KeyStrokeMapping is still causing headaches ;-)

I would like to see your solution (PR) and will merge it so that other users can participate from your work.

**Comment by croesch** [comment]
Thanks for the quick PR. I would merge it but did find the following. Could you please check if that is exactly what you need?

AssertJ Swing has the ability to define the keyboard layout via
```
-Dassertj.swing.keyboard.locale=fr
```

If I understand the code then this should be exactly what you initially needed!? Right?

**Comment by fmarot** [comment]
Nice catch ! I'll test it soon and report the result here.
Thanks !

**Comment by fmarot** [comment]
Perfect, I'm happy to announce your suggestion works as expected.  I should have dug deeper.
Big thanks !

**Comment by croesch** [comment]
Not a problem.. me too :)
