### ISSUE TITLE
Question: How to launch two app simultaneously

### ISSUE THREAD

**Issue by dextercarrasco** [joel-costigliola/assertj-swing#207]
I have this requirement to launch the app with certain parameters, input some data and then retrieve the same data in the same app launched with different parameters. Can this be done? I tried calling ApplicationLauncher twice with different parameters but it doesn't work. Closing the frame terminates the whole test.

**Comment by dextercarrasco** [comment]
It seems I can cleanup the frame and later launch the application again.

**Comment by croesch** [comment]
Okay so problem solved? Normally it depends heavily on your main methods logic and what the Frame does when it get's closed. But it's possible to run the application twice, yes.
