### ISSUE TITLE
Create test class without extending AssertJSwingJUnitTestCase class

### ISSUE THREAD

**Issue by widura** [joel-costigliola/assertj-swing#219]
There is a requirement that need to implement AssertJSwingJUnitTestCase class features in our own class hierarchy, But there is a constraints for extending AssertJSwingJUnitTestCase class. Is it recommended to implement setup Robot and handle FailOnThreadViolationRepaintManager in our own class level.

**Comment by croesch** [comment]
Of course you can write your own base test class, however I would recommend using `AssertJSwingJUnitTestCase`. What's the reason for not using it?

If you cannot use it, it's a good idea to implement the same things as the [base test class](https://joel-costigliola.github.io/assertj/assertj-swing-basics.html#base-test-case).

Hope that helps, just reopen the issue if you have further questions / suggestions. Thx.
