### ISSUE TITLE
Assertj-swing stopped working after upgrading to MACOS-X mojave

### ISSUE THREAD

**Issue by zolyfarkas** [joel-costigliola/assertj-swing#224]
App window shows up, but event simulation does not seem to happen.

Running with Oracle JDK 1.8.0 u181

**Comment by croesch** [comment]
Hello @zolyfarkas 

thanks for opening this short issue. Unfortunately I don't have access to MacOs, so I can't help you with that. But I'm looking forward reviewing and merging your pull requests :)

best regards

**Comment by zolyfarkas** [comment]
@croesch if you can give me some tips into where should I look into it would help with coming up with a fix, I am not familiar with the innards of assertj.

let me know.

thank you

**Comment by peanball** [comment]
Hi @zolyfarkas,
the issue is with security / privacy settings in MacOS.
Apps that remote control the mouse / keyboard now need to be approved explicitly to avoid malware.

To enable e.g. Eclipse, go to System Preferences > Security & Privacy > Accessibility and add Eclipse to the list of applications on the right.

**Comment by smccants** [comment]
Any idea how to do this when the test application is being launched via WebStart?

**Comment by peanball** [comment]
Who’s launching it? Do you have a Build Script that ultimately calls javaws? Then you may want to add Terminal.app or whatever you’re using to start it.

**Comment by smccants** [comment]
Actually, we are using it in a technical demo.  Our salesman launches the demo via downloading a JNLP file and then presses a key which lets the Robot do some things (change the configuration of our system, which we don't want the sales guy to be doing).

**Comment by smccants** [comment]
We set the web browser to be an Accessibility application and that fixed the problem.  Thanks for your help @peanball !

**Comment by zolyfarkas** [comment]
@peanball worked, thanks!
