### ISSUE TITLE
I need to know if it is capable of launching a windows executable file for an application that is using java swing. Can i able to launch the .exe for the application under test using assertj

### ISSUE THREAD

**Issue by udhaya-aj** [joel-costigliola/assertj-swing#231]

**Comment by DaveBrad** [comment]
May I suggest you use Java's ProcessBuilder class to launch your .exe file. AssertJ is java file.

I'm not understanding 'windows executable file for an application that is using java swing'. Has the Java-swing been placed/converted into an .exe? if so I don't see how from my knowledge of FEST/ASSERTJ.

May I assume that the .exe is 'launching' a java jar from within the .exe. Thus the .exe has launched an independent Java application. The Java swing application is then interacted with.
-- by the .exe file [I don't see how assertj could interact through the .exe UI, as it is not Java]
-- as a Java GUI window a user would interact directly with the Java app (in this case the .exe has no part in the UI. So test the Java swing app via 'package org.assertj.swing.launcher; ApplicationLauncher.application' as an independent GUI from the .exe file.

 I suspect this is a none issue and likely not possible considering Java and .exe files are very different architecture.

To help joel,, can this be closed.
