### ISSUE TITLE
How to extend an existing AssertJ Swing fixture - outdated docs?

### ISSUE THREAD

**Issue by donobarro** [joel-costigliola/assertj-swing#236]
Hi,

I have some custom Swing components in my project and I want to create some additional fixtures that are going to work with them.

https://joel-costigliola.github.io/assertj/assertj-swing-advanced.html
I want to start from scratch, so according to above manual, I need to extend class ComponentFixture OR GenericComponentFixture. 

The problem is none of these classes exist in AssertJ Swing and I really do not know what to do now. Any hints?

**Comment by croesch** [comment]
Hi @donobarro 

Thanks for the information that the documentation is outdated and sorry for that.
I updated the [documentation](https://joel-costigliola.github.io/assertj/assertj-swing-advanced.html).

Have a look at the type hierarchy of [AbstractComponentFixture](https://joel-costigliola.github.io/assertj/swing/api/org/assertj/swing/fixture/AbstractComponentFixture.html) and look for the best extension point.

Let us know if anything is missing, outdated or different than you expect it to be.

Thanks for your help!

**Comment by croesch** [comment]
I guess the question is answered, reopen if not :-)
