### ISSUE TITLE
GUI-Tests on a VNC server

### ISSUE THREAD

**Issue by nesseb** [joel-costigliola/assertj-swing#238]
I wrote a few GUI tests and now I not have idea how run this without taking control of the mouse. On page there is information to use tightVNC but there is only java-viewer no serwer. I tried use MacOs Screen Sharing but here too I don't know how run tests from maven. On now I have installed a tightVNC server on Windows XP on VirtualBox, I can connect from my mac by tightvnc-jviewer.jar to this server, but when I execute bash script execute-on-vnc.sh I got error:  "vncserver: command not found". 
Please help me resolve my problem.

**Comment by croesch** [comment]
Sorry for not answering this long time. Is this still relevant for you?

Basically you have to check how you can run a command on the vncserver - if you started it and your UI automatically opens in the vnc server you can just run 

    mvn test

The `execute-on-vnc.sh` should be used as an example if you are working with other commands / operating systems (than Ubuntu). It doesn't do any magic you need, just make sure that when `mvn test` runs, it uses the vnc server as UI and that depends on the operating system you're working on. So you're working on MacOs? I guess you just need to change the command for spawning the vncserver. I think running the vncserver on another machine is not working in this easy script of mine - it's meant to connect to a vnc display on the localhost machine.

Reopen if still relevant :-)
