### ISSUE TITLE
Unable to take screenshot when I run the test suite via Jenkins which is a linux server. 

### ISSUE THREAD

**Issue by croesch** [joel-costigliola/assertj-swing#94]
_Issue by **[Rattan Behl](http://jira.codehaus.org/secure/ViewProfile.jspa?name=rattanbehl)** from Tue, 22 Nov 2011 23:48:53 -0600_
_Originally opened as http://jira.codehaus.org/browse/FEST-457_

---

<p>Steps:<br/>
When I try to run the test suite on my local machine (which is Mac Pro) it works fine.<br/>
But, on running it via Jenkins (Unix server) I get the following exception:<br/>
<span class="error">&#91;testng&#93;</span> SEVERE: Unable to create ScreenshotTaker<br/>
   <span class="error">&#91;testng&#93;</span> org.fest.swing.image.ImageException: Unable to create AWT Robot<br/>
   <span class="error">&#91;testng&#93;</span>  at org.fest.swing.image.ScreenshotTaker.&lt;init&gt;(ScreenshotTaker.java:67)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.fest.swing.image.ScreenshotTaker.&lt;init&gt;(ScreenshotTaker.java:58)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.fest.swing.testng.listener.ScreenshotOnFailureListener.&lt;init&gt;(ScreenshotOnFailureListener.java:73)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.fest.swing.testng.ScreenshotOnFailureListener.&lt;init&gt;(ScreenshotOnFailureListener.java:25)<br/>
   <span class="error">&#91;testng&#93;</span>  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>
   <span class="error">&#91;testng&#93;</span>  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)<br/>
   <span class="error">&#91;testng&#93;</span>  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)<br/>
   <span class="error">&#91;testng&#93;</span>  at java.lang.reflect.Constructor.newInstance(Constructor.java:513)<br/>
   <span class="error">&#91;testng&#93;</span>  at java.lang.Class.newInstance0(Class.java:355)<br/>
   <span class="error">&#91;testng&#93;</span>  at java.lang.Class.newInstance(Class.java:308)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:48)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.testng.TestNG.setListenerClasses(TestNG.java:654)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.testng.TestNG.configure(TestNG.java:1271)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.testng.TestNG.privateMain(TestNG.java:1172)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.testng.TestNG.main(TestNG.java:1146)<br/>
   <span class="error">&#91;testng&#93;</span> Caused by: java.awt.AWTException: headless environment<br/>
   <span class="error">&#91;testng&#93;</span>  at java.awt.Robot.&lt;init&gt;(Robot.java:75)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.fest.swing.util.RobotFactory.newRobotInPrimaryScreen(RobotFactory.java:35)<br/>
   <span class="error">&#91;testng&#93;</span>  at org.fest.swing.image.ScreenshotTaker.&lt;init&gt;(ScreenshotTaker.java:65)<br/>
   <span class="error">&#91;testng&#93;</span>  ... 14 more</p>

<p>I refereed the URL - <a href="https://github.com/behrica/fest-swing-1.x/commit/c7380ed1a8062a8be53b2042db871b5de0985e6e" class="external-link" rel="nofollow">https://github.com/behrica/fest-swing-1.x/commit/c7380ed1a8062a8be53b2042db871b5de0985e6e</a><br/>
I made the changes which were specific to fest-swing and added the two files - <br/>
1) IScreenshotTaker.java<br/>
2) NoopScreenshotTaker.java</p>

<p>And modified the following file:<br/>
1)ScreenshotTaker.java</p>

<p>As I'm using TestNg so I ignored the changes which were mentioned for JUNIT. </p>

<p>But, still I'm getting the same error as I have pasted above.</p>

<p>Excepted Behavior:<br/>
Should take the screenshot of the test failure on the remote machine through a Unix machine.</p>

---

votes (original issue): 0
watches (original issue): 0

**Comment by anandukanagaraj** [comment]
Hi ... I am facing the same issue, could you please provide the solution you have.

**Comment by croesch** [comment]
Of course the robot cannot be created in headless environments. See for example [stackoverflow: headless-environment-error-in-java-awt-robot-class-with-mac-os](https://stackoverflow.com/questions/13487025/headless-environment-error-in-java-awt-robot-class-with-mac-os)
